# Generated by Django 5.0.14 on 2026-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_inmueble', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento')], default='DEPARTAMENTO', max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('gastos_comunes', models.IntegerField()),
                ('cuartos', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('correo_contacto', models.EmailField(max_length=254)),
            ],
        ),
    ]
