# Generated by Django 5.0.14 on 2026-10-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenciaInmobiliariaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='numero_depto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Depto / Unidad'),
        ),
    ]
